### ISSUE TITLE
Install g_mmpbsa error

### ISSUE THREAD

**Issue by yccai** [RashmiKumari/g_mmpbsa#10]
I install g_mmpbsa in linux system, but I encounter an error, as following:
'''
-- checking for module 'libgromacs'
--   package 'libgromacs' not found
-- Could NOT find GROMACS (missing:  GROMACS_LIBRARY) 
-- Continue checking for other Gromacs version library file
-- checking for module 'libgmx'
--   package 'libgmx' not found
-- Could NOT find GROMACS (missing:  GROMACS_LIBRARY) 
CMake Error at src/CMakeLists.txt:72 (message):
  

  Gromacs path is not defined.....

  USE:

   -DGMX_PATH=/path/to/gromacs
    or  
   export CMAKE_PREFIX_PATH="/path/to/gromacs"

-- Configuring incomplete, errors occurred!
'''
This is my command:
'''cmake -DGMX_PATH=/home/rwshi/soft/gmx465-1/ -DAPBS_INSTALL=//home/dpli/software/apbs -DAPBS_SRC=/home/dp
li/software/apbs-1.3-source -DCMAKE_INSTALL_PREFIX=/home/dpli/software/g_mmpbsa ..'''

**Comment by rjdkmr** [comment]
Above error shows that gromacs library file is not present in given GMX_PATH directory. 

Why not use already complied version of g_mmpbsa.

Please report these type of problem in g_mmpbsa mailing list.
