### ISSUE TITLE
builtins module

### ISSUE THREAD

**Issue by mohammad392** [RashmiKumari/g_mmpbsa#11]
Hi All,

I executed the "python MmPbSaStat.py -m energy_MM.xvg -p polar.xvg -a apolar.xvg" command. But, I got the following error:

Traceback (most recent call last):
  File "MmPbSaStat.py", line 39, in <module>
    from builtins import range
ImportError: No module named builtins

Can you please help me figure this out?

Regards,
Mohammad

**Comment by hmarlo** [comment]
The builtins module comes from the package "future", so `pip install future` in your Python environment should solve the problem.
