### ISSUE TITLE
Can't reproduce the full output of the tutorial

### ISSUE THREAD

**Issue by hmarlo** [RashmiKumari/g_mmpbsa#13]
Hey! I've downloaded the tutorial and run the bash inside it and it's not generating certain output that comes with the tutorial.

Anyone knows something?

Thank you!

**Comment by rjdkmr** [comment]
Which outputs are missing or different? The output in tutorials were generated using Gromacs-4.5.x versions.

**Comment by hmarlo** [comment]
The calculations are fine, but the plots, summaries, subunits, etc. are not generated. Only the XVGs.

**Comment by rjdkmr** [comment]
Yes, those are generated manually, therefore not included in the tutorial data. Commands are provided in the tutorial, and you can generate these files with these commands.

**Comment by hmarlo** [comment]
Ah! I will take a better look, thank you :)
