### ISSUE TITLE
error in LIG PB energy"

### ISSUE THREAD

**Issue by nehachaudhary769** [RashmiKumari/g_mmpbsa#2]
Hello, 
I am trying to do MM_PBSA calculations of Protein-Ligand complex. I am getting an error in polar.xvg; there is a text "nan" instead of numericals in the column for Lig PB energy. Please let me know what is the error. The same error "nan" was observed in Electrostatic energy between Protein-LIgand and also in Binding energy of Ligand calculated at later stage. Kindly let me know what should be done.

**Comment by rjdkmr** [comment]
Hello,

You have npt provided any additional information to track the problem. Kindly give the information how you are doing the calculations. Have you corrected the molecule for PBC?

**Please post the problem in [g_mmpbsa mailing list](https://groups.google.com/forum/#!forum/g_mmpbsa).** Here in Github, problems are only posted for bugs in software.

Thanks.

With best regards,
Rajendra
