### ISSUE TITLE
MmPbSaDecomp indentation (MacOS)

### ISSUE THREAD

**Issue by adhaimovich** [RashmiKumari/g_mmpbsa#3]
MmPbSaDecomp.py has the following issue:
python ./tools/MmPbSaDecomp.py -bs -nbs 2000 -m contrib_MM.dat -p contrib_pol.dat -a contrib_apol.dat
  File "./tools/MmPbSaDecomp.py", line 133
    args = parser.parse_args()
    ^
IndentationError: unexpected indent

I apologize if I am missing something trivial.

**Comment by rjdkmr** [comment]
Kindly find the corrected script in this post: https://groups.google.com/forum/#!topic/g_mmpbsa/40U9K8wspwg

We will upload the corrected script in next release.

**Comment by adhaimovich** [comment]
This works quite well. Thank you!

Adrian

From: Rajendra Kumar
Reply-To: RashmiKumari/g_mmpbsa
Date: Friday, August 7, 2015 at 5:37 AM
To: RashmiKumari/g_mmpbsa
Cc: Adrian Haimovich
Subject: Re: [g_mmpbsa] MmPbSaDecomp indentation (MacOS) (#3)


Kindly find the corrected script in this post: https://groups.google.com/forum/#!topic/g_mmpbsa/40U9K8wspwg<https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_forum_-23-21topic_g-5Fmmpbsa_40U9K8wspwg&d=AwMCaQ&c=-dg2m7zWuuDZ0MUcV7Sdqw&r=Vm3HILe5bIr9KDn0eonv7OuMW9uIGR_-bsfsp9lQX-k&m=ll8jxfQO7yym6BY8tI5rtVqD3Zu_sKCbVMUeQZOqWxA&s=S_SyatiUAv-J-bL7Y65NSx05JYvEYIVGUCDlASX8Qq8&e=>

We will upload the corrected script in next release.
