### ISSUE TITLE
Segmentation fault      (core dumped)

### ISSUE THREAD

**Issue by AspirinCode** [RashmiKumari/g_mmpbsa#6]
----------------------------------------------------------------------
	APBS also uses Aqua to solve the Poisson-Boltzmann equation numerically.  
	Aqua is a modified form of the Holst group PMG library <http://www.FEtk.ORG>
	which has been modified by Patrice Koehl
	<http://koehllab.genomecenter.ucdavis.edu/> for improved efficiency and
	memory usage when solving the Poisson-Boltzmann equation.
----------------------------------------------------------------------
	Please cite your use of APBS as:

	Baker NA, Sept D, Joseph S, Holst MJ, McCammon JA. Electrostatics of
	nanosystems: application to microtubules and the ribosome. Proc.
	Natl. Acad. Sci. USA 98, 10037-10041 2001.
	

This executable compiled on Apr 19 2016 at 23:49:16

Parsing input file pzI1YbtA.in...
calculate_energy.sh: line 6:  5604 Done                    echo 1 13
      5605 Segmentation fault      (core dumped) | g_mmpbsa -f 1EBZ.xtc -s 1EBZ.tpr -n 1EBZ.ndx -i ../polar.mdp -nomme -pbsa -decomp
                   :-) GROMACS - g_mmpbsa, VERSION 5.1.2 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov  Herman J.C. Berendsen    Par Bjelkmar   
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra   Sebastian Fritsch 
  Gerrit Groenhof   Christoph Junghans   Anca Hamuraru    Vincent Hindriksen
 Dimitrios Karkoulis    Peter Kasson        Jiri Kraus      Carsten Kutzner  
    Per Larsson      Justin A. Lemkul   Magnus Lundborg   Pieter Meulenhoff 
   Erik Marklund      Teemu Murtola       Szilard Pall       Sander Pronk   
   Roland Schulz     Alexey Shvetsov     Michael Shirts     Alfons Sijbers  
   Peter Tieleman    Teemu Virolainen  Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2015, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

##################################################################
second steps，Calculation of polar solvation energy

get  error“Segmentation fault      (core dumped)” ，others is OK。

**Comment by diallobakary4** [comment]
Experiencing a similar problem running the command: 
`g_mmpbsa -f md.xtc -s md.tpr -n index.ndx -i pbsa.mdp -b 20000 -dt 10 -pdie 2 -pbsa -decomp`
Any help?

**Comment by Debamitraiit** [comment]
Experiencing a similar problem running the command:
g_mmpbsa -f md.xtc -s md.tpr -n index.ndx -i pbsa.mdp -b 20000 -dt 10 -pdie 2 -pbsa -decomp
Any help? Could you solve it
