### ISSUE TITLE
RAM memory problems

### ISSUE THREAD

**Issue by bieniekmateusz** [RashmiKumari/g_mmpbsa#7]
I have a large dataset and I've just noticed that my process is killed. 

My dmesg says that the process took over 20GB:

> Killed process 14036 (g_mmpbsa) total-vm:26639468kB

I presume this means that the entire simulation is loaded to the RAM memory. If that's true, is this really necessary? Thanks

**Comment by rjdkmr** [comment]
No, g_mmpbsa does not load the entire trajectory in RAM. However, polar solvation energy calculation requires large RAM that depend on grid-size, cfac, fadd and molecule size.

**Comment by bieniekmateusz** [comment]
So this must be a memory leak issue. I have a small system and each time I use your software on a single trajectory, I am slowly running out of memory. And using simple tools suxh as 'ps' and 'top' I can see your process acumulating ever larger size of RAM memory.

**Comment by rjdkmr** [comment]
If it is memory leak, it is very difficult to track memory leak because g_mmpbsa uses APBS code internally and we are unable to check for APBS code. You may try to use g_mmpbsa, which uses APBS externally. In this case we could trace memory leak.

**Comment by bieniekmateusz** [comment]
I'll run an additional test with just MM to see if this problem is due to APBS. 

Right now after around 100 frames (and around 100,000 skipped frames) the software crashes on any modern machine.

**Comment by bieniekmateusz** [comment]
Using only MM does not lead to memory crash so this must be coming from APBS. 

Do I understand it right that you using the binary file from APBS? If that is the case, then simply restarting the software would clean the memory heap. 

Thanks for your help.

**Comment by bieniekmateusz** [comment]
I could not reproduce the issue. I imagine that it must have been some error on my part. It could the a PBC issue or something like that. 

Thanks for your help, Mat

**Comment by haseeb3389** [comment]
Dear @rjdkmr  I was calculating the g_mmpbsa and due to power failure my system shutdown, is there anyway to restart from the previous or I have to re-calculate from start?
