### ISSUE TITLE
-pbsa should be switched on by default

### ISSUE THREAD

**Issue by bieniekmateusz** [RashmiKumari/g_mmpbsa#8]
If I understand right, the main reason behind the existence of this package is the PBSA calculation. I've used your software naively just to realise that I only did the MM part later when I read the paper. But in some way this is very ironic and misleading that you can run software called mmpbsa and it by default only does not do pbsa. I believe this should be by default switched on.

**Comment by rjdkmr** [comment]
-pbsa used to be switched on by default during development phase. However, PB calculation could take lot of RAM and Processing. Therefore, this option acts as a check for user that they are starting PB calculation with correct parameters. 
Moreover, I do not expect that this tool should be used naively. At first, user should know about MM/PBSA theory before using this method. MM/PBSA comes with limitations and it cannot be used for every cases. Therefore, a literature reading is must before using this method.

**Comment by bieniekmateusz** [comment]
This is an issue. It is confusing without any reason. You're implying that the "lots of processing" is a check for the user to know whether PB is running, which sounds like a terrible idea. Just because the software is slow at something that should not be used to convey other information. 

You basically run "mmpbsa" and you have to tell the software to switch on pbsa. In that case you could have just call it "mm".

**Comment by bieniekmateusz** [comment]
Just to compare, you call the software "copy_and_paste" and by default turn off the "paste" part. The suggestion that the user always should be fully competent regarding the software even in the beginning is naive.

**Comment by rjdkmr** [comment]
This tool should not be used naively. There are lot of parameters which could be changed. For example, one do not run Gromacs mdrun without knowing about parameters in mdp files.

**Comment by bieniekmateusz** [comment]
No tool should be used naively. But that is not a reason to make something more confusing than it already is.
